# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'QuarantineBuddies' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Pods for QuarantineBuddies
  pod 'Firebase'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
pod 'MessageKit'
  inherit! :search_paths
end
